name: release

on:
  push:
    tags:
      - "*"

jobs:
  trigger-generate:
    runs-on: ubuntu-latest
    needs: [goreleaser]
    steps:
      - uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          repo: goreleaser/goreleaser
          ref: main
          token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
